# Generates the search-friendly parts of the public site from index.html + assets/js/data.js:
#   articles/<slug>.html  one real page per post (full text in the HTML, title, description,
#                         share-preview tags, BlogPosting structured data)
#   sitemap.xml, robots.txt, .nojekyll
#   and refreshes the home page's own meta tags in index.html.
# Run after editing posts:   powershell -ExecutionPolicy Bypass -File tools\build-pages.ps1
# Change the public address: ... -File tools\build-pages.ps1 -SiteUrl https://blog.fangviper.com
param([string]$SiteUrl)
$ErrorActionPreference = "Stop"
$root = Split-Path $PSScriptRoot -Parent
$cfg = Join-Path $PSScriptRoot "site-url.txt"
$utf8 = New-Object System.Text.UTF8Encoding($false)
function Read-Text($p) { [IO.File]::ReadAllText($p, [Text.Encoding]::UTF8) }
function Write-Text($p, $t) { [IO.File]::WriteAllText($p, $t, $utf8) }
function Esc([string]$s) { $s.Replace('&', '&amp;').Replace('"', '&quot;').Replace('<', '&lt;').Replace('>', '&gt;') }
function JsonEsc([string]$s) { $s.Replace('\', '\\').Replace('"', '\"') }
function Set-Region([string]$text, [string]$name, [string]$content) {
  $startTag = "<!-- build:$name"
  $endTag = "<!-- /build:$name -->"
  $s = $text.IndexOf($startTag)
  $e = $text.IndexOf($endTag)
  if ($s -lt 0 -or $e -lt 0) { throw "index.html is missing the build:$name markers" }
  return $text.Substring(0, $s) + $content + $text.Substring($e + $endTag.Length)
}

if ($SiteUrl) { Write-Text $cfg $SiteUrl } else { $SiteUrl = (Read-Text $cfg).Trim() }
$SiteUrl = $SiteUrl.TrimEnd('/')
$brand = "Fang Viper Journal"
$dash = [string][char]0x2014   # em dash, written by code so the script stays plain ASCII
$homeDesc = "The Fang Viper Journal: no-fluff motivation, training, nutrition and recovery for people who show up when nobody's watching."

# ---- read posts from data.js ------------------------------------------------
$data = Read-Text (Join-Path $root "assets\js\data.js")
$rx = [regex]'(?s)\{\s*slug:\s*"(?<slug>[^"]+)".*?title:\s*"(?<title>[^"]*)".*?category:\s*"(?<cat>[^"]*)".*?date:\s*"(?<date>[^"]*)".*?excerpt:\s*"(?<excerpt>[^"]*)".*?cover:\s*\{(?<cover>[^}]*)\}.*?body:\s*`(?<body>.*?)`\s*\}'
$posts = @()
foreach ($m in $rx.Matches($data)) {
  $src = ([regex]'src:\s*"([^"]+)"').Match($m.Groups['cover'].Value).Groups[1].Value
  $posts += [pscustomobject]@{
    slug = $m.Groups['slug'].Value; title = $m.Groups['title'].Value; cat = $m.Groups['cat'].Value
    date = $m.Groups['date'].Value; excerpt = $m.Groups['excerpt'].Value; body = $m.Groups['body'].Value.Trim()
    image = $(if ($src) { $src } else { "assets/img/hero-lift.jpg" })
  }
}
if ($posts.Count -eq 0) { throw "No posts found in data.js" }

$tpl = Read-Text (Join-Path $root "index.html")

# ---- home page meta ---------------------------------------------------------
$homeMeta = @"
<!-- build:meta (generated by tools/build-pages.ps1) -->
  <title>$brand</title>
  <meta name="description" content="$(Esc $homeDesc)">
  <link rel="canonical" href="$SiteUrl/">
  <meta property="og:type" content="website">
  <meta property="og:site_name" content="$brand">
  <meta property="og:title" content="$brand">
  <meta property="og:description" content="$(Esc $homeDesc)">
  <meta property="og:url" content="$SiteUrl/">
  <meta property="og:image" content="$SiteUrl/assets/img/hero-lift.jpg">
  <meta name="twitter:card" content="summary_large_image">
  <!-- /build:meta -->
"@
$tpl = Set-Region $tpl "meta" $homeMeta
Write-Text (Join-Path $root "index.html") $tpl

# ---- article pages ----------------------------------------------------------
$outDir = Join-Path $root "articles"
New-Item -ItemType Directory -Force $outDir | Out-Null
Get-ChildItem $outDir -Filter *.html | Remove-Item

# shared page shell: no intro loader, no home sections, links point back to the home page
$shell = Set-Region $tpl "preloader" ""
$shell = Set-Region $shell "home" ""
$shell = $shell -replace 'href="#journal" data-cat-link="(\w+)"', 'href="index.html?cat=$1#journal" data-cat-link="$1"'
$shell = $shell.Replace('href="#challenge"', 'href="index.html#challenge"')
$shell = $shell.Replace('<div class="curtain" aria-hidden="true">', '<div class="curtain curtain--boot" aria-hidden="true">')

foreach ($p in $posts) {
  $url = "$SiteUrl/articles/$($p.slug).html"
  $img = "$SiteUrl/$($p.image)"
  $dateText = [datetime]::ParseExact($p.date, 'yyyy-MM-dd', [cultureinfo]::InvariantCulture).ToString('MMM d, yyyy', [cultureinfo]'en-US')
  $ld = '{"@context":"https://schema.org","@type":"BlogPosting","headline":"' + (JsonEsc $p.title) + '","description":"' + (JsonEsc $p.excerpt) +
        '","datePublished":"' + $p.date + '","dateModified":"' + $p.date + '","image":"' + $img + '","mainEntityOfPage":"' + $url +
        '","author":{"@type":"Organization","name":"Fang Viper"},"publisher":{"@type":"Organization","name":"Fang Viper","logo":{"@type":"ImageObject","url":"' + $SiteUrl + '/assets/img/logo-black.png"}}}'
  $meta = @"
<!-- build:meta (generated by tools/build-pages.ps1) -->
  <base href="../">
  <title>$(Esc $p.title) $dash $brand</title>
  <meta name="description" content="$(Esc $p.excerpt)">
  <link rel="canonical" href="$url">
  <meta property="og:type" content="article">
  <meta property="og:site_name" content="$brand">
  <meta property="og:title" content="$(Esc $p.title)">
  <meta property="og:description" content="$(Esc $p.excerpt)">
  <meta property="og:url" content="$url">
  <meta property="og:image" content="$img">
  <meta property="article:published_time" content="$($p.date)">
  <meta name="twitter:card" content="summary_large_image">
  <script type="application/ld+json">$ld</script>
  <!-- /build:meta -->
"@
  $article = @"
<!-- build:article -->
  <main id="main" class="article-view" data-article data-slug="$($p.slug)">
    <header class="a-hero container">
      <a class="a-back" href="index.html#journal">Back to the journal</a>
      <div class="a-kicker"><b>$(Esc $p.cat)</b><span>$dateText</span><span>By Fang Viper</span></div>
      <h1 class="a-title">$(Esc $p.title)</h1>
      <p class="a-dek">$(Esc $p.excerpt)</p>
    </header>
    <div class="a-layout container">
      <article class="prose" id="article-body">
"@ + $p.body + @"

      </article>
    </div>
  </main>
  <!-- /build:article -->
"@
  $page = Set-Region $shell "meta" $meta
  $page = Set-Region $page "article" $article
  $page = $page.Replace('<a class="skip" href="#journal">Skip to articles</a>', "<a class=""skip"" href=""articles/$($p.slug).html#article-body"">Skip to article</a>")
  Write-Text (Join-Path $outDir "$($p.slug).html") $page
}

# ---- sitemap, robots, .nojekyll --------------------------------------------
$latest = ($posts | Sort-Object date -Descending | Select-Object -First 1).date
$urls = @("  <url><loc>$SiteUrl/</loc><lastmod>$latest</lastmod></url>")
foreach ($p in $posts) { $urls += "  <url><loc>$SiteUrl/articles/$($p.slug).html</loc><lastmod>$($p.date)</lastmod></url>" }
Write-Text (Join-Path $root "sitemap.xml") ("<?xml version=""1.0"" encoding=""UTF-8""?>`n<urlset xmlns=""http://www.sitemaps.org/schemas/sitemap/0.9"">`n" + ($urls -join "`n") + "`n</urlset>`n")
Write-Text (Join-Path $root "robots.txt") "User-agent: *`nAllow: /`nDisallow: /tools/`n`nSitemap: $SiteUrl/sitemap.xml`n"
Write-Text (Join-Path $root ".nojekyll") ""

Write-Host "Built $($posts.Count) article pages, sitemap.xml and robots.txt for $SiteUrl"
if ($SiteUrl -match "USERNAME") { Write-Host "Note: site address is still a placeholder. Re-run with -SiteUrl once the GitHub address is known." }
